-- ----------------------------------------------------------------------------
-- Antecedentes del usuario (alergias, enfermedades cronicas, condiciones
-- hereditarias) y citas.
--
-- Estos cinco modulos se escribieron en la rama `dev`, donde el esquema lo
-- creaba Hibernate con ddl-auto=update y no habia migraciones. Aqui Hibernate
-- solo valida (ddl-auto=validate), asi que sin esta migracion el backend no
-- arranca: las entidades Alergia, EnfermedadCronica, CondicionHereditaria,
-- TipoCita y Cita no tendrian tabla.
--
-- Las columnas siguen a las entidades tal como vienen de `dev`: los
-- identificadores son Integer con GenerationType.IDENTITY, de ahi INTEGER
-- GENERATED BY DEFAULT AS IDENTITY, y los largos son los de sus @Size.
--
-- ── Por que cuelgan de users y no de pacientes ─────────────────────────────
-- Las entidades de `dev` apuntan a User (user_id), no a Paciente. Se respeta
-- en esta migracion para no reescribir los modulos al integrarlos; mover los
-- antecedentes y las citas a pacientes (persona_id) es trabajo pendiente, y se
-- hara en una migracion propia cuando se decida.
-- ----------------------------------------------------------------------------

-- Los antecedentes se borran con su usuario: la entidad User los declara con
-- cascade = ALL y orphanRemoval, y esto lo replica en la base.
CREATE TABLE public.alergias (
    alergia_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(100) NOT NULL,
    tipo                VARCHAR(100) NOT NULL,
    severidad           VARCHAR(50)  NOT NULL,
    reaccion_reportada  VARCHAR(255) NOT NULL,
    user_id             INTEGER NOT NULL
        REFERENCES public.users (user_id) ON DELETE CASCADE
);

CREATE INDEX alergias_user_id_idx ON public.alergias (user_id);

CREATE TABLE public.enfermedades_cronicas (
    enfermedad_cronica_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                 VARCHAR(100) NOT NULL,
    anio                   INTEGER      NOT NULL,
    tratamiento            VARCHAR(255) NOT NULL,
    user_id                INTEGER NOT NULL
        REFERENCES public.users (user_id) ON DELETE CASCADE
);

CREATE INDEX enfermedades_cronicas_user_id_idx ON public.enfermedades_cronicas (user_id);

CREATE TABLE public.condiciones_hereditarias (
    condicion_hereditaria_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                    VARCHAR(100) NOT NULL,
    parentesco                VARCHAR(100) NOT NULL,
    observaciones             VARCHAR(255),
    user_id                   INTEGER NOT NULL
        REFERENCES public.users (user_id) ON DELETE CASCADE
);

CREATE INDEX condiciones_hereditarias_user_id_idx ON public.condiciones_hereditarias (user_id);

CREATE TABLE public.tipos_cita (
    tipo_cita_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(100) NOT NULL,
    descripcion   VARCHAR(255)
);

-- Una cita es registro de agenda: borrar al paciente, al medico o un tipo de
-- cita no puede llevarse las citas por delante. RESTRICT, igual que
-- signos_vitales.enfermera_id en V9.
CREATE TABLE public.citas (
    cita_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_user_id  INTEGER NOT NULL
        REFERENCES public.users (user_id) ON DELETE RESTRICT,
    fecha_hora        TIMESTAMP NOT NULL,
    tipo_cita_id      INTEGER NOT NULL
        REFERENCES public.tipos_cita (tipo_cita_id) ON DELETE RESTRICT,
    medico_user_id    INTEGER NOT NULL
        REFERENCES public.users (user_id) ON DELETE RESTRICT,
    estado            VARCHAR(30) NOT NULL
);

CREATE INDEX citas_paciente_user_id_idx ON public.citas (paciente_user_id);
CREATE INDEX citas_medico_user_id_idx   ON public.citas (medico_user_id);
